# EvaluateTransitions.srv

# Request: list of transition names to evaluate
string[] transition_names

---
# Response: overall result and detailed results for each transition
bool overall_success                         # Indicates if all transitions were successfully evaluated
string message                               # General message or summary information
colav_interfaces/TransitionResult[] results # Detailed result for each transition