# UpdateDynamics.srv: a service request for the dynamic update
# Request
string mode

---

# Response
bool success
string success_message
int32 mode_num
colav_interfaces/CRUISEDynamics cruise
colav_interfaces/T2LOSDynamics t2los 
colav_interfaces/T2ThetaDynamics t2theta 
colav_interfaces/FBDynamics fb 
colav_interfaces/WaypointReachedDynamic waypoint_reached
