name: colav_interfaces CI/CD
run-name: ${{ github.actor }} is testing colav_interfaces 🚀

on:
  push: 
    branches: [main]
  pull_request:
    branches: [main]
  release: 
    types: [created, prereleased, published]

jobs: 
  build: 
    runs-on: ubuntu-latest
    container:
      image: ros:humble-ros-core
    
    steps:
      - name: Install Git
        run: apt-get update && apt-get install -y git

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          path: ros2_ws/src

      - name: Setup ROS2 workspace
        run: |
          cd /ros2_ws
          colcon build
          source install/setup.bash

      - name: Run Tests
        run: |
          cd /ros2_ws
          colcon test