name: colav_interfaces CI/CD
run-name: ${{ github.actor }} is testing colav_interfaces 🚀

on:
  push: 
    branches: [main]
  pull_request:
    branches: [main]
  release: 
    types: [created, prereleased, published]

jobs: 
  build: 
    runs-on: ubuntu-latest
    container:
      image: ros:humble-ros-core
    
    steps:
      - name: Install Dependencies
        run: |
          apt-get update && apt-get install -y \
            build-essential \
            cmake \
            python3-pip \
            python3-colcon-common-extensions \
            ros-humble-ament-cmake
      
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          path: colav_interfaces  # Checkout to a subfolder in the workspace
    
  compile:
    name: Compile colav_interfaces pkg
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          path: colav_interfaces  # Checkout to a subfolder in the workspace

      - name: Setup ROS2 workspace
        run: |
          mkdir -p /ros2_ws/src/colav_interfaces
          mv $GITHUB_WORKSPACE/colav_interfaces/* /ros2_ws/src/colav_interfaces

      - name: Build ROS2 workspace
        shell: bash
        run: |
          cd /ros2_ws
          source /opt/ros/humble/setup.bash
          colcon build --packages-select colav_interfaces
          source install/setup.bash

  test:
    name: test colav_interfaces pkg
    needs: compile
    runs-on: ubuntu-latest
    steps:  
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          path: colav_interfaces  # Checkout to a subfolder in the workspace

      - name: Run Tests
        run: |
          cd /ros2_ws
          source /opt/ros/humble/setup.bash
          source /ros2_ws/install/setup.bash
          colcon test --event-handlers console_cohesion+
          colcon test-result --verbose
          cd /ros2_ws
          source /opt/ros/humble/setup.bash
          source /ros2_ws/install/setup.bash
          colcon test --event-handlers console_cohesion+
          colcon test-result --verbose
